# Generated by Django 4.0.6 on 2022-07-23 14:22

from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=250, verbose_name='عنوان')),
                ('name_en', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='لینک')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوع ها',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=250, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='لینک')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, to='portfolio.category', verbose_name='موضوع ها')),
            ],
            options={
                'verbose_name': 'پورتفوی',
                'verbose_name_plural': 'پورتفوی ها',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام و توضیحات')),
                ('video', models.FileField(upload_to='portfolio/videos/', verbose_name='انتخاب فایل')),
                ('default', models.BooleanField(default=False, verbose_name='انتخاب به عنوان پیشفرض')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.portfolio', verbose_name='انتخاب مقصد')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام و توضیحات')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='portfolio/images/', verbose_name='انتخاب فایل')),
                ('default', models.BooleanField(default=False, verbose_name='انتخاب به عنوان پیشفرض')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio', verbose_name='انتخاب مقصد')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام و توضیحات')),
                ('item', models.FileField(upload_to='portfolio/files/', verbose_name='انتخاب فایل')),
                ('default', models.BooleanField(default=False, verbose_name='انتخاب به عنوان پیشفرض')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portfolio.portfolio', verbose_name='انتخاب مقصد')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
    ]
