# Generated by Django 4.0.6 on 2022-07-20 15:38

from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='لینک')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوع ها',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='لینک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', image_optimizer.fields.OptimizedImageField(blank=True, upload_to='images/', verbose_name='انتخاب عکس')),
                ('video', models.FileField(blank=True, upload_to='videos/', verbose_name='انتخاب ویدیو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, to='portfolio.category', verbose_name='موضوع ها')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='media.imagealbum', verbose_name='آلبوم تصاویر')),
                ('videos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='media.videoalbum', verbose_name='آلبوم ویدیو ها')),
            ],
            options={
                'verbose_name': 'پورتفوی',
                'verbose_name_plural': 'پورتفوی ها',
                'ordering': ['-updated'],
            },
        ),
    ]
