# Generated by Django 4.0.4 on 2022-07-11 16:09

from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آلبوم')),
            ],
            options={
                'verbose_name': 'آلبوم فایل',
                'verbose_name_plural': 'آلبوم فایل ها',
            },
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آلبوم')),
            ],
            options={
                'verbose_name': 'آلبوم تصاویر',
                'verbose_name_plural': 'آلبوم تصاویر',
            },
        ),
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام آلبوم')),
            ],
            options={
                'verbose_name': 'آلبوم ویدیو',
                'verbose_name_plural': 'آلبوم ویدیوها',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و توضیحات')),
                ('video', models.FileField(upload_to=media.models.get_video_upload_path, verbose_name='انتخاب فایل')),
                ('default', models.BooleanField(default=False, verbose_name='انتخاب به عنوان پیشفرض')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media.videoalbum', verbose_name='انتخاب آلبوم')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و توضیحات')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to=media.models.get_image_upload_path, verbose_name='انتخاب فایل')),
                ('default', models.BooleanField(default=False, verbose_name='انتخاب به عنوان پیشفرض')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media.imagealbum', verbose_name='انتخاب آلبوم')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و توضیحات')),
                ('item', models.FileField(upload_to=media.models.get_file_upload_path, verbose_name='انتخاب فایل')),
                ('default', models.BooleanField(default=False, verbose_name='انتخاب به عنوان پیشفرض')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='media.filealbum', verbose_name='انتخاب لیست')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
    ]
